name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Maven
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run tests and generate JaCoCo report
        run: ./gradlew clean test jacocoTestReport

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/build/report/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60